### ISSUE TITLE
Add config item to specify inference framework.

### ISSUE THREAD

**Issue by madgrizzle** [OpenVoiceOS/ovos-ww-plugin-openWakeWord#5]
openwakeword now allows you to select between inference frameworks (onnx or tflite).  tflite is the default so onnx won't work as is.  I'm making a PR to add 'inference_framework' as a config item.

**Comment by j1nx** [comment]
Hi there, perhaps any news on this item?

It might save me from runing into thesame error as indeed tflite is now the default inference framework.

**Comment by dscripka** [comment]
This is fixed in the latest `0.4.0` release, you can now include `inference_framework` as a config item to specify either `onnx` or `tflite` manually.
